import type { MediaType } from "./types";

// Real titles with real TMDB poster paths, so even in mock mode (no TMDB
// key) posters load from TMDB's public image CDN. Used as the candidate
// pool when TMDB/RapidAPI/Gemini keys are absent, so the whole flow is
// clickable without live keys. Ids, posters, and overviews were pulled
// live from TMDB to make sure every poster path actually resolves.
export interface MockTitle {
  tmdb_id: number;
  imdb_id: string;
  media_type: MediaType;
  title: string;
  year: number;
  poster_path: string;
  imdb_rating: number;
  runtime: number;
  overview: string;
  genres: number[];
  original_language: string;
}

export const MOCK_TITLES: MockTitle[] = [
  { tmdb_id: 27205, imdb_id: "tt1375666", media_type: "movie", title: "Inception", year: 2010, poster_path: "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg", imdb_rating: 8.4, runtime: 148, overview: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets, is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.", genres: [28, 878, 12], original_language: "en" },
  { tmdb_id: 155, imdb_id: "tt0468569", media_type: "movie", title: "The Dark Knight", year: 2008, poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg", imdb_rating: 8.5, runtime: 152, overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.", genres: [28, 53, 80], original_language: "en" },
  { tmdb_id: 496243, imdb_id: "tt6751668", media_type: "movie", title: "Parasite", year: 2019, poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", imdb_rating: 8.5, runtime: 133, overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", genres: [35, 53, 18], original_language: "ko" },
  { tmdb_id: 20453, imdb_id: "tt1187043", media_type: "movie", title: "3 Idiots", year: 2009, poster_path: "/66A9MqXOyVFCssoloscw79z8Tew.jpg", imdb_rating: 8.0, runtime: 171, overview: "From the moment he arrives at India's most prestigious university, Rancho's outlandish schemes turn the campus upside down, along with the lives of his two newfound best friends.", genres: [18, 35], original_language: "hi" },
  { tmdb_id: 360814, imdb_id: "tt5074352", media_type: "movie", title: "Dangal", year: 2016, poster_path: "/cJRPOLEexI7qp2DKtFfCh7YaaUG.jpg", imdb_rating: 7.9, runtime: 161, overview: "An extraordinary true story based on the life of Mahavir Singh and his two daughters, Geeta and Babita Phogat, tracing the journey of a father who trains his daughters to become world-class wrestlers.", genres: [18, 10751, 35], original_language: "hi" },
  { tmdb_id: 491625, imdb_id: "tt2395469", media_type: "movie", title: "Gully Boy", year: 2019, poster_path: "/h57EzPdrDvtUkvbTj6ar5yZOPic.jpg", imdb_rating: 7.3, runtime: 156, overview: "Murad, an underdog, struggles to convey his views on social issues and life in Dharavi through rapping. His life changes drastically when he meets a local rapper, Shrikant alias MC Sher.", genres: [18, 10402], original_language: "hi" },
  { tmdb_id: 579974, imdb_id: "tt8178634", media_type: "movie", title: "RRR", year: 2022, poster_path: "/u0XUBNQWlOvrh0Gd97ARGpIkL0.jpg", imdb_rating: 7.7, runtime: 187, overview: "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.", genres: [28, 36, 18], original_language: "te" },
  { tmdb_id: 157336, imdb_id: "tt0816692", media_type: "movie", title: "Interstellar", year: 2014, poster_path: "/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg", imdb_rating: 8.5, runtime: 169, overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival, conquering the vast distances involved in an interstellar voyage.", genres: [12, 18, 878], original_language: "en" },
  { tmdb_id: 278, imdb_id: "tt0111161", media_type: "movie", title: "The Shawshank Redemption", year: 1994, poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg", imdb_rating: 8.7, runtime: 142, overview: "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, finding solace and eventual redemption.", genres: [18, 80], original_language: "en" },
  { tmdb_id: 680, imdb_id: "tt0110912", media_type: "movie", title: "Pulp Fiction", year: 1994, poster_path: "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg", imdb_rating: 8.5, runtime: 154, overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.", genres: [53, 80, 35], original_language: "en" },
  { tmdb_id: 313369, imdb_id: "tt3783958", media_type: "movie", title: "La La Land", year: 2016, poster_path: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg", imdb_rating: 7.9, runtime: 129, overview: "Mia, an aspiring actress, and Sebastian, a jazz musician, are faced with decisions that begin to fray the fragile fabric of their love affair as success mounts.", genres: [35, 18, 10749], original_language: "en" },
  { tmdb_id: 120467, imdb_id: "tt2278388", media_type: "movie", title: "The Grand Budapest Hotel", year: 2014, poster_path: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg", imdb_rating: 8.0, runtime: 100, overview: "The legendary concierge of a famous European hotel and his friendship with a young employee who becomes his trusted protégé, amid the theft and recovery of a priceless Renaissance painting.", genres: [35, 18], original_language: "en" },
  { tmdb_id: 419430, imdb_id: "tt5052448", media_type: "movie", title: "Get Out", year: 2017, poster_path: "/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg", imdb_rating: 7.6, runtime: 104, overview: "Chris and his girlfriend Rose go upstate to visit her parents for the weekend, where a series of increasingly disturbing discoveries lead him to a truth he never could have imagined.", genres: [9648, 53, 27], original_language: "en" },
  { tmdb_id: 447332, imdb_id: "tt6644200", media_type: "movie", title: "A Quiet Place", year: 2018, poster_path: "/nAU74GmpUk7t5iklEp3bufwDq4n.jpg", imdb_rating: 7.4, runtime: 91, overview: "A family is forced to live in silence while hiding from creatures that hunt by sound.", genres: [27, 18, 878], original_language: "en" },
  { tmdb_id: 475557, imdb_id: "tt7286456", media_type: "movie", title: "Joker", year: 2019, poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", imdb_rating: 8.1, runtime: 122, overview: "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.", genres: [80, 53, 18], original_language: "en" },
  { tmdb_id: 372058, imdb_id: "tt5311514", media_type: "movie", title: "Your Name.", year: 2016, poster_path: "/vfJFJPepRKapMd5G2ro7klIRysq.jpg", imdb_rating: 8.5, runtime: 106, overview: "High schoolers Mitsuha and Taki are complete strangers living separate lives, until one night they suddenly begin switching places.", genres: [16, 10749, 18], original_language: "ja" },
  { tmdb_id: 66732, imdb_id: "tt4574334", media_type: "tv", title: "Stranger Things", year: 2016, poster_path: "/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg", imdb_rating: 8.6, runtime: 50, overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.", genres: [10759, 9648, 10765], original_language: "en" },
  { tmdb_id: 1396, imdb_id: "tt0903747", media_type: "tv", title: "Breaking Bad", year: 2008, poster_path: "/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg", imdb_rating: 9.0, runtime: 47, overview: "A New Mexico chemistry teacher diagnosed with cancer teams with a former student to secure his family's financial future through the dangerous world of drugs and crime.", genres: [18, 80], original_language: "en" },
  { tmdb_id: 71446, imdb_id: "tt6468322", media_type: "tv", title: "Money Heist", year: 2017, poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg", imdb_rating: 8.2, runtime: 50, overview: "A mysterious man called The Professor recruits a band of eight robbers to carry out the biggest heist in history, holed up in the National Coinage and Stamp Factory of Spain.", genres: [80, 18], original_language: "es" },
  { tmdb_id: 1668, imdb_id: "tt0108778", media_type: "tv", title: "Friends", year: 1994, poster_path: "/kuqCom4s0htI5POztRTxxYrswqt.jpg", imdb_rating: 8.4, runtime: 22, overview: "Six young people from New York City, on their own and struggling to survive in the real world, find companionship, comfort and support in each other.", genres: [35], original_language: "en" },
  { tmdb_id: 79352, imdb_id: "tt6077448", media_type: "tv", title: "Sacred Games", year: 2018, poster_path: "/uEbNtFbK4At9WBDGap23lt1qO9n.jpg", imdb_rating: 7.8, runtime: 50, overview: "A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.", genres: [18, 80, 10759], original_language: "hi" },
  { tmdb_id: 84105, imdb_id: "tt6473300", media_type: "tv", title: "Mirzapur", year: 2018, poster_path: "/1rxLUFVrtTo82OxhbDXJDiJVkwL.jpg", imdb_rating: 8.0, runtime: 45, overview: "An incident at a wedding procession forces a mafia don's unworthy heir to cross paths with an upstanding lawyer and his sons, snowballing into a game of ambition, power and greed.", genres: [80, 10759, 18], original_language: "hi" },
  { tmdb_id: 2316, imdb_id: "tt0386676", media_type: "tv", title: "The Office", year: 2005, poster_path: "/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg", imdb_rating: 8.6, runtime: 22, overview: "The everyday lives of office employees in the Scranton, Pennsylvania branch of the fictional Dunder Mifflin Paper Company.", genres: [35], original_language: "en" },
  { tmdb_id: 93352, imdb_id: "tt9544034", media_type: "tv", title: "The Family Man", year: 2019, poster_path: "/tE1NUJqw9gV6AVjQ1GTK78LbWJ9.jpg", imdb_rating: 7.7, runtime: 50, overview: "A middle-class man works for a special cell of the National Investigation Agency, trying to protect the nation from terrorists while also protecting his family from the fallout of his secretive job.", genres: [18, 10759], original_language: "hi" },
  { tmdb_id: 63174, imdb_id: "tt4052886", media_type: "tv", title: "Lucifer", year: 2016, poster_path: "/ekZobS8isE6mA53RAiGDG93hBxL.jpg", imdb_rating: 8.4, runtime: 45, overview: "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandons his throne and retires to Los Angeles, where he teams up with an LAPD detective to take down criminals.", genres: [80, 10765], original_language: "en" },
  { tmdb_id: 1418, imdb_id: "tt0898266", media_type: "tv", title: "The Big Bang Theory", year: 2007, poster_path: "/euKFiO5M125rpngFRBbSW83beeI.jpg", imdb_rating: 7.9, runtime: 22, overview: "Physicists Leonard and Sheldon find their nerd-centric social circle expanding when aspiring actress Penny moves in next door.", genres: [35], original_language: "en" },
  { tmdb_id: 8587, imdb_id: "tt0110357", media_type: "movie", title: "The Lion King", year: 1994, poster_path: "/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg", imdb_rating: 8.3, runtime: 89, overview: "Young lion prince Simba, eager to one day become king of the Pride Lands, must confront his past and find his rightful place in the Circle of Life after tragedy and betrayal.", genres: [16, 10751, 18], original_language: "en" },
  { tmdb_id: 244786, imdb_id: "tt2582802", media_type: "movie", title: "Whiplash", year: 2014, poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg", imdb_rating: 8.4, runtime: 107, overview: "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.", genres: [18, 10402, 53], original_language: "en" },
];
